jpignata/temping

README.md

Fixing a small typo, also remove trailing white space.

Fix a small typo.

---

README.md
lib/temping.rb
spec/spec_helper.rb
spec/temping_spec.rb

I added `Temping::teardown` in order to solve #18. This method drops all tables and undefines all constants introduced by Temping. It's now possible to use Temping in `setup`/`before` blocks.
The change is fully backward compatible. If `Temping::teardown` is not called the code behaves exactly as before.
I had to introduce a monkey patch (d'oh!) in the spec helper in order to write an expectation. `#table_exists?` offered by Active Record (at least the SQLite adapter) does _not_ work for temporary tables. See the comment above the monkey patch for more details.
`teardown` should be called from `teardown`/`after` blocks in order to clean up tables and objects created by Temping. Without it it's not possible to use Temping in a `setup`/`before` block and reuse the same temporary model in …

Add Temping::teardown

---

.travis.yml
CONTRIBUTING.md
Gemfile.lock
README.md
Rakefile
spec/config.default.yml
spec/spec_helper.rb
spec/test_config.rb
temping.gemspec

I implemented a simple multi-database test mechanism (inspired by [Active Record test tasks](https://github.com/rails/rails/blob/master/activerecord/Rakefile)). The adapters are configured in `spec/config.default.yml`. Before running the tests, a one-time setup is required:
```
$ rake db:mysql:create db:postgresql:create
```
The credentials that are used to create the database are specified in `spec/config.default.yml`. After the databases are created you can run the specs like:
```
$ rake # or rake spec - runs the specs against all adapters
$ rake spec:mysql
$ rake spec:postgresql
$ rake spec:sqlite3
```
[The Travis build](https://travis-ci.org/grn/temping) was successful.
Configuration logic related to tests is implemented in `spec/test_config.rb`. The module is responsible for parsing …

Add automated multi-database tests

---

Rakefile
lib/temping.rb
spec/temping_spec.rb

Hey, this patches an issue when you create multiple models with Temping with the same name. AR will load the column information once, but not after. Calling reset_column_information after the schema update fixes it. Let me know if there's anything I should change!
I started a new PR to re-run the Travis build, for some reason it failed and I couldn't replicate it locally.

Reset column information

---

lib/temping.rb
spec/temping_spec.rb

I need an ability to generate temporary PostgreSQL table with UUID primary keys. So I have to pass additional options to `create_table` method.

Add abiltity to override create_table options

---

README.md
lib/temping.rb
spec/temping_spec.rb

Hello 
I implemented `Temping.cleanup` method. It is very helpful when you want to test statically defined models.
```ruby
RSpec.describe SomeModelConcern do 
Temping.create User
after do 
Temping.cleanup
end 
include_examples "concern behaviour", User
end 
```

Implement Temping.cleanup

---

lib/temping.rb
spec/temping_spec.rb

* Rails 5 models now inherit from the ApplicationRecord abstract class, so
Temping will set the generated model's superclass accordingly if the
ActiveRecord major version is greater than 4

Adds support for Rails 5 ApplicationRecord

---

lib/temping.rb
spec/temping_spec.rb

From errors reported in https://github.com/jpignata/temping/issues/45
this adds the `clear_dependencies` option to the `teardown` method,
making it optional to clear dependencies.

Add option to clear dependencies in `teardown` method.

---

README.md
lib/temping.rb
spec/temping_spec.rb

Like #48 I also had a need for this, so I whipped up an implementation that's almost exactly the same except it names the option `parent_class`. I debated using just `parent` but felt that might not be specific enough.
Per the discussion on #48, I added README and specs.
Thanks to @jetaggart  for making this easy 😁

Add option for specifying parent class

---

temping.gemspec

To allow automated tools (such as LicenseFinder [https://github.com/pivotal/LicenseFinder]) to detect and
report licenses in use by a system and its dependencies.
Further details here: https://github.com/pivotal/LicenseFinder#a-plea-to-package-authors-and-maintainers

Setting license in gem package spec.

---

CHANGELOG.md

Update Changelog to drop support of Rails below 6 and ruby below 2.5

Update Changelog to drop support of Rails below 6

---

lib/temping.rb

This line of code produced a deprecation warning in Ruby 2.7 and now fails in Ruby 3.0.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Use explicit kwargs double splat for Ruby 3+

---

.github/workflows/tests.yml

YAML in .github/workflows/tests.yaml of ruby versions is parsed as integers which leads to problems for ruby `3.0`, it is parsed as `3` which in turn translates to `3.1`.
Fixing this.

Fix ruby versions in CI

---

CHANGELOG.md
lib/temping.rb
spec/spec_helper.rb
spec/temping_spec.rb

Fixes #67 
Previously there was added some code in https://github.com/jpignata/temping/pull/40 to handle cases when models created by Temping are cached in ActiveRecord (ActiveSupport?) reflection store.
However in Rails 7 autoloading was hugely reworked, most of the code from ActiveSupport::Dependencies was deleted as described in https://rubyonrails.org/2021/9/3/autoloading-in-rails-7-get-ready, so this whole problem seems to be gone. At the very least I can't reproduce the exception from the test case added in https://github.com/jpignata/temping/pull/40 with ActiveRecord 7 (if I just remove `ActiveSupport::Dependencies::Reference.clear!`). 
So, let's just try removing that line for Rails >= 7.

Fix Rails 7

---

lib/temping.rb
spec/temping_spec.rb

Remove mentions of old versions of Rails from the code and specs.

Remove mentions of old versions of Rails

---

.github/workflows/tests.yml
CONTRIBUTING.md
Rakefile
lib/temping.rb
spec/spec_helper.rb
spec/temping_spec.rb
spec/test_config.rb
temping.gemspec

Integrate [standardrb](https://github.com/testdouble/standard) into CI.
Fail workflows if offenses found.
(This will be just indicative without any consequence since maintainers can merge any PR anyway even if the coverage is less than 100%).

Integrate standardrb into CI

---

.standard.yml
Appraisals
gemfiles/activerecord_5.2.gemfile
gemfiles/activerecord_6.0.gemfile
gemfiles/activerecord_6.1.gemfile
gemfiles/activerecord_7.0.gemfile
temping.gemspec

Changes:
* Return activesupport back as explicit dependency
* Specify 2.0.0 as a ruby version for StandardRB linter (as a minimum supported version)

Return activesupport back as explicit dependency

---

CHANGELOG.md
README.md
lib/temping.rb
lib/temping/model_factory.rb
lib/temping/namespace_factory.rb
spec/temping_spec.rb

Closes feature request #17.
Now if Temping detects you wanted to create a namespace for your model it will create it if it doesn't exist yet or use the existing one. During `.teardown` it will undefine all the modules from the namespace previously created by itself.
A fresh entry in the Readme:
--
Temping supports creating models within namespaces. 
You can do this either by just including the full namespace in the name:
```ruby
Temping.create('animal/cat')
Animal::Cat.create # => <Animal::Cat id: 1>
Animal::Cat.table_name # => "cats"
Animal::Cat # => Animal::Cat(id: integer)
```
Or you can create the module(s) yourself:
```ruby
module Engineers
def self.table_name_prefix
"hard_working_"
end
end
Temping.create('engineers/developers')
Engineers::Developer.create # => <Engineers::Developer …
```

Support namespaces

---

.github/workflows/checks.yml
.standard.yml
CHANGELOG.md
README.md
Rakefile
spec/spec_helper.rb
spec/test_config.rb
temping.gemspec

Changes:
1. Add ruby 2.2 and 2.3 to CI. These only work with SQLite however ([mysql fail](https://github.com/ruby/setup-ruby/issues/150#issuecomment-767760333), [postgresql fail](https://github.com/dmytro-savochkin/temping/actions/runs/3405123075/jobs/5662861593)) with the current setup of Github Actions. This is still better than nothing because this at least confirms all the used syntax in the gem works with these versions of ruby.
2. Set minimum requirement version of Ruby to be 2.2.2. This is what [Rails 5.2 specifies](https://github.com/rails/rails/blob/5-2-stable/rails.gemspec) and since it's the lowest version of Rails we support we should just specify the same.

Adjust ruby version requirement to 2.2.2 and add 2.2 and 2.3 to CI

---

CHANGELOG.md
temping.gemspec

Bump version to 4.0.0.
Full changelog can be found here: https://github.com/jpignata/temping/blob/master/CHANGELOG.md

Bump v4.0.0

---

temping.gemspec

Fix warnings from Rubygems while building temping gem:
```
WARNING:  open-ended dependency on appraisal (..., development) is not recommended
WARNING:  open-ended dependency on standard (..., development) is not recommended
```

Fix open ended dependency warning from Rubygems

---

CHANGELOG.md
temping.gemspec

Bump version to 4.1.0.
Full changelog can be found here: https://github.com/jpignata/temping/blob/master/CHANGELOG.md

Bump v4.1.0

---

CHANGELOG.md
temping.gemspec

Bump version to 4.1.1.
Full changelog can be found here: https://github.com/jpignata/temping/blob/master/CHANGELOG.md

Bump v4.1.1

---

CHANGELOG.md
temping.gemspec

Bump version to 4.2.0.
Full changelog can be found here: https://github.com/jpignata/temping/blob/master/CHANGELOG.md

Bump v4.2.0

---

.github/workflows/checks.yml
Appraisals
CONTRIBUTING.md
Gemfile
README.md
docker-compose.yml
gemfiles/activerecord_6.0.gemfile
gemfiles/activerecord_6.1.gemfile
gemfiles/activerecord_7.0.gemfile
gemfiles/activerecord_7.1.gemfile
gemfiles/activerecord_7.2.gemfile
gemfiles/activerecord_8.0.gemfile
spec/config.default.yml
temping.gemspec

*Issue #, if available:* —
*Description of changes:*
* Add support for Rails 8.0
* Add Ruby 3.3, Rails 8.0, PostgreSQL 17, MySQL 9.1 to tests
* Remove MySQL 5.5 from tests as its support ended in 2018 and it’s not supported by Rails 8.0
* Upgrade versions of GitHub actions to fix deprecation warnings
> [!IMPORTANT]  
> The only test failing is [this one](https://github.com/talkable/temping/actions/runs/11778095884/job/32804291774):
> > Please make sure test coverage is 100%. Currently: 100% (line), 97.14% (branch).
>
> Not sure why branch coverage decreased, any suggestions are welcome.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Support Rails 8.0
